### PR TITLE
mesh materialViewer should always have a material

### PR DESCRIPTION
**Pull request by manavortex**
generate a default material if we don't have one

### CODE REVIEW

**Comment by rfuzzo** [comment]
This looks good and sounds reasonable. but we change the mesh right? can that have unintended consequences? What if I delete the default material manually again? will it be created again?

**Comment by manavortex** [comment]
true... but we don't mark anything as dirty, so there's a good chance the user will just overwrite? :| 
I guess we could delete the stuff again when leaving the appearance tab

**Comment by rfuzzo** [comment]
not sure.. we could also just mark dirty, that works for me as well. what do you think?

**Comment by manavortex** [comment]
should print a console message in that case. I dunno, I like the other one more, I currently have lots of material-less meshes because of ArchiveXL appearance patching :D

**Review by rfuzzo — APPROVED** [review]
thx, lgtm

**Pull request merged**
