### PR TITLE
WIP/broken fix garment support based on intel by psi

### PR DESCRIPTION
**Pull request by manavortex**
image
@DoctorPresto please check if this works

### CODE REVIEW

**Comment by DoctorPresto** [comment]
not quite :D

````[2024-05-13 11:41:12 PM] [Error    ] Message: Unable to cast object of type 'WolvenKit.RED4.Types.meshMeshParamGarmentSupport' to type 'WolvenKit.RED4.Types.garmentMeshParamGarment'.
Source: System.Private.CoreLib
StackTrace:    at WolvenKit.Modkit.RED4.Tools.MeshTools.WriteGarmentParametersToMesh(List`1& meshes, CMesh cMesh, Boolean exportGarmentSupport) in C:\Users\danma\source\repos\WolvenKit\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 1457
   at WolvenKit.Modkit.RED4.Tools.MeshTools.GetModel(CR2WFile cr2w, Boolean lodFilter, Boolean includeRig, UInt64 chunkMask, Boolean mergeMeshes, Boolean exportGarmentSupport) in C:\Users\danma\source\repos\WolvenKit\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 84
   at WolvenKit.Modkit.RED4.Tools.MeshTools.ExportMesh(CR2WFile cr2w, FileInfo outfile, MeshExportArgs meshExportArgs, ValidationMode vMode) in C:\Users\danma\source\repos\WolvenKit\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 34
   at WolvenKit.Modkit.RED4.ModTools.ExportMesh(CR2WFile cr2w, FileInfo outfile, MeshExportArgs meshExportArgs, ValidationMode vmode) in C:\Users\danma\source\repos\WolvenKit\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 1014
   at WolvenKit.Modkit.RED4.ModTools.HandleMesh(CR2WFile cr2wFile, FileInfo cr2wFileName, MeshExportArgs meshargs) in C:\Users\danma\source\repos\WolvenKit\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 1022
   at WolvenKit.Modkit.RED4.ModTools.InternalUncookBuffers(CR2WFile cr2wFile, String relPath, FileInfo outfile, GlobalExportArgs settings, DirectoryInfo rawOutDir) in C:\Users\danma\source\repos\WolvenKit\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 533````

**Comment by manavortex** [comment]
image
... uhh

**Comment by effs** [comment]
I'm not quite sure what's being fixed here. Best I can tell, the full garmentsupport data is both read and written as a single span per mesh, but differentiated in the cr2w so that `garmentMeshBlob` (`meshMeshParam..`) contains the caps and `garmentBlob` (`garmentMeshParam..`) contains everything else.

This works correctly for fem. Export is already conditional on `garmentMeshParam` so absence of the `meshMeshParam` shouldn't be an issue.

But symptom is that the pma `.mesh` (not `.morphtarget`) contains no shapekey when exported?

**Comment by manavortex** [comment]
I think the PMA mesh has no... I don't even know. Caps by default? I just tried to do what Presto told me, he and psi know more about this :D

**Pull request closed without merging**
