### PR TITLE
Project explorer: context menu "copy relative path"

### PR DESCRIPTION
**Pull request by manavortex**
# Further refactoring made it less horrible 

but ffs syncfusion why

# Modifier states and logic

| Modifier State   | Context Menu Entry  | Context Menu Behaviour  |
|---|---|---|
| none   | Copy relative path to game file  | Copies relative path to game file. For files under /raw/, will try to generate the correct .archive path.  | 
| Shift  | Copy absolute path  | Copies the absolute path to the current file, for e.g. opening it in photoshop  |
| Ctrl  | Copy absolute path to current folder | Copies the absolute path to the current folder, for e.g. pasting it into Windows Explorer  |
| Ctrl+Shift  | Copy absolute path to <archive/raw> folder | Copies the absolute path to the _other_ folder (if you're in .archive, it'll switch to .raw and vice versa) |

Further refactoring:

https://github.com/WolvenKit/WolvenKit/assets/965785/a800c072-3fbb-417f-b9f6-7d836ad359c6

### CODE REVIEW

**Comment by seberoth** [comment]
What's the difference to #1611 ?

**Comment by manavortex** [comment]
I need to get those update events untangled

**Comment by manavortex** [comment]
It should be good to go o_o

**Review by rfuzzo — APPROVED** [review]
Approving now

**Pull request merged**
