### PR TITLE
Update wwtools Windows lib to not be in debug mode

### PR DESCRIPTION
**Pull request by ADawesomeguy**
Just recompiled the DLL using the release configuration.

### CODE REVIEW

**Comment by ADawesomeguy** [comment]
Don't merge yet, gotta make an updated DLL.

**Comment by ADawesomeguy** [comment]
Alright now it should be good.

**Review by rfuzzo — APPROVED** [review]
I reviewed all code changes and found nothing.

**Comment by ADawesomeguy** [comment]
This is a deep statement on the very meaning of life.

**Pull request merged**
