### PR TITLE
fixing regenerate visual controllers

### PR DESCRIPTION
**Pull request by manavortex**
# fixing regenerate visual controllers

### CODE REVIEW

**Comment by poirierlouis** [comment]
Looks more like a refactor than a fix no?

**Comment by manavortex** [comment]
I fixed it by renaming the command to what's actually called... so maybe both :D

**Comment by poirierlouis** [comment]
Oh, the command used in XAML was not Visible, but Visual. Hence the fix?

**Comment by manavortex** [comment]
Yeah, it's supposed to be Visual :D

**Pull request merged**
