### PR TITLE
mesh material: more fallback upon export failures, better logging

### PR DESCRIPTION
**Pull request by manavortex**
I hope this didn't break the singleton

### CODE REVIEW

**Review by seberoth — CHANGES_REQUESTED** [review]
Pls don't do that. Pass it down like everywhere else.
Would create a second instance. Also won't work with CLI

**Comment by manavortex** [comment]
> Pls don't do that. Pass it down like everywhere else. Would create a second instance. Also won't work with CLI

Alright, that was what I didn't know :) How _do_ I pass it down? I followed the chain two or three hops, and didn't find any loggers

**Comment by seberoth** [comment]
`ModTools` has `_loggerService`
Add it to `MaterialExtractor` (also as `_loggerService`) and pass it into its constructor

**Review by seberoth — APPROVED** [review]
lgtm

**Pull request merged**
