### PR TITLE
Add libs to main directory and reference them by name and not path

### PR DESCRIPTION
**Pull request by ADawesomeguy**
The whole lib subdirectoy was a problematic so I think it's better to reference them by name in the main directory as it's not platform-specific.

Also fixes the issue where it tries to load a Linux lib on Windows.

### CODE REVIEW

**Review by rfuzzo — APPROVED** [review]
I trust you that it works on Linux.

**Comment by ADawesomeguy** [comment]
I trust you that you checked.

**Comment by ADawesomeguy** [comment]
> I trust you that it works on Linux. 

I'll test it out again before you merge.

**Comment by ADawesomeguy** [comment]
Ok it worked, maybe test on Windows. Also keep in mind this will move all the libs to the main build directory instead of the lib subdirectory but is infinitely more convenient for P/Invoke.

**Comment by rfuzzo** [comment]
Ok

**Comment by ADawesomeguy** [comment]
Sooo.... does that mean this should be merged?

**Pull request merged**
