### PR TITLE
feat: add UI scaling + improve UX

### LINKED ISSUE #604: Font/UI scaling
**Is your feature request related to a problem? Please describe.**
First World Problems incarnate: On my 4k monitor, the font of WolvenKit is all but unreadable.

**Describe the solution you'd like**
UI scaling! It would be grand to have it configurable via settings dialogue.

**Describe alternatives you've considered**
- I thought about font scaling in case UI scaling is complex, but that will likely mess up the entire UI. 
- I've looked around in case one of the config-looking files had a value for this, but didn't find anything.
- Lowering the resolution feels kind of meh.

**Additional context**
If you really need a screenshot, I can provide one later today if you tell me to :)

### PR DESCRIPTION
**Pull request by poirierlouis**
# feat: add UI scaling + improve UX

**Implemented:**
- [x] Add dynamic resources for:
  - [x] font size
  - [x] icon size
  - [x] margin/padding
- [x] Trick `SfSkinManager` to dynamically change theme settings
  - It somehow breaks window's rendering when settings are reloaded. Minimising/maximising window workarounds this issue. Either show a message box to user, that WKit needs to restart, or find a fix to prevent greyish background...
- [ ] Define scale based on screen's height at startup, when not already defined manually by the user.
> Use height only to account for wider screen ratio.
- [x] Add IconBox to provide uniform boxing/scaling.
- [x] HomePage
  - [x] `HomePageView`
  - [x] [WelcomePageView](https://github.com/user-attachments/assets/74473f7a-101b-420a-a410-d94b5c16973a)
  - [x] [SettingsPageView](https://github.com/user-attachments/assets/167b250b-6194-4bcd-8015-1b287f3d742c)
    - changed icon in favor of outline style
    - changed fields submit event to 'focus out/enter'
    - limit `Scale UI (%)` between 100% and 900%
  - [x] [PluginsToolView](https://github.com/user-attachments/assets/d9de4853-daf1-4b66-8093-5bbf567cc12f)
  - [x] [ModsView](https://github.com/user-attachments/assets/e7f9650c-c0cc-4e2f-acd5-bdea22fdc082)
    - moved buttons in header (like other Home views)
- [x] Shell
  - [x] `BackStageView`
  - [x] [DockingAdapter](https://github.com/user-attachments/assets/28f4617c-9966-4df3-b282-2a41f750fdf3)
  - [x] `MainView`
  - [x] [MenuBarView](https://github.com/user-attachments/assets/d68e9430-1b96-4c40-8dd4-e72afcb764c7) (*screenshot not up-to-date*)
    - changed icons in favor of outline style
    - uniformed colors
  - [x] [RibbonView](https://github.com/user-attachments/assets/c9cb79d3-772c-4b3c-9f2d-6514eed032e1)
    - changed icons in favor of outline style
    - uniformed colors
  - [x] `Splash`
  - [x] `StatusBarView`
- [ ] Tools
  - [x] [AssetBrowserView](https://github.com/user-attachments/assets/6a6850e0-eec0-41c6-95bc-bce3ac30c543) [[old]](https://github.com/user-attachments/assets/b4ae28e0-0de8-418d-81b5-18d24e9a4597)
    - changed icons (find buttons / open in new tab)
    - added missing icons
  - [x] [AudioPlayerView](https://github.com/user-attachments/assets/f518a722-ecd1-4636-aea0-1a3966d8fc0f)
  - [x] [HashToolView](https://github.com/user-attachments/assets/14e1a908-ad9e-4070-ac85-2616f1a967e1)
  - [x] [LocKeyBrowserView](https://github.com/user-attachments/assets/a0df1317-3ef5-4ba2-9632-8a5d2baafde8)
    - minimized height of rows
    - moved secondary key in its own row
    - added scroll behavior for LocKey preview
  - [x] [LogView](https://github.com/user-attachments/assets/53a0bf46-2110-4cd6-b676-c4822ee1dbf0)
  - [x] [ProjectExplorerView](https://github.com/user-attachments/assets/7bb91a22-002c-4cea-963b-55b18d9a4a85) [[old]](https://github.com/user-attachments/assets/d039ae39-7638-40a7-8aca-8a33f0438d9c)
    - moved search bar in its own row
    - changed icons with uniform style
    - changed icon to open in a new tab
    - colorized few icons
    - toggle icon of tree/flat button
  - [x] [PropertiesView](https://github.com/user-attachments/assets/8d7a5b86-2751-4a93-92d2-77596e1971d4)
  - [ ] RedColorPicker
    - depends on ColorPicker which cannot be modified as-is, afaik.
  - [x] [RedTreeView](https://github.com/user-attachments/assets/e1e496fa-4cbf-4ac4-9fe6-8e76b1753e3f) [[old]](https://github.com/user-attachments/assets/6707bb01-fc9c-4061-ad14-c4ac2f6f8594)
    - fixed alignment when tree's width is changed.
    - changed icons with uniform style
    - colorized icons
  - [x] [TweakBrowserView](https://github.com/user-attachments/assets/675dca41-43ef-427e-877b-0bf719fe4ad5)
    - removed expander for Filters: straightforward access
    - changed icon with uniform style
    - colorized icon
    - refactored loading logic to always show form fields but disable them when loading. Use Converters instead of a UI type field in ViewModel/XAML ([review](https://github.com/user-attachments/assets/c4948ada-fad0-4859-ab55-187929689e9b)).
    - **leads**
      - PR to add a Load button like in Asset Browser: always wait for user to ask TweakDB to load. Otherwise, mouse hovering docker panel on the right will start the loading process, while it was not even asked by the user.
- [x] Dialogs
  - [x] Windows
    - [x] [ChangeComponentChunkMaskDialog](https://github.com/user-attachments/assets/3b3cce28-1707-469b-9131-a1430a8989a1)
    - [x] [ChooseCollectionView](https://github.com/user-attachments/assets/32178524-0db7-4bae-8c43-15ac204f00a0)
    - [x] [CreateMaterialsDialog](https://github.com/user-attachments/assets/0d819098-9311-4a09-8c40-886b9dd56d07)
    - [x] [DeleteOrMoveFilesListDialogView](https://github.com/user-attachments/assets/c153c3bc-0f5b-4d00-91ea-db44aa1b1bc6)
    - [x] [FirstSetupView](https://github.com/user-attachments/assets/c5a9ae2b-0b95-40bc-823f-73a43265c7b4)
    - [x] [LaunchProfilesView](https://github.com/user-attachments/assets/941b3e73-ee43-4622-8cf2-7d728ab849e6)
      - fixed profile ordering: disable sorting
    - [x] [MaterialsRepositoryDialog](https://github.com/user-attachments/assets/a1fd009c-bb69-426b-bb24-25b7c7a56e7f)
    - [x] [RenameDialog](https://github.com/user-attachments/assets/12f6466d-9bf1-42da-b600-f4ac6b75dd90)
    - [x] [SaveGameSelectionDialog](https://github.com/user-attachments/assets/f62a3cf7-1a68-40e9-8887-13bdabd0e232)
    - [x] [SearchAndReplaceDialogView](https://github.com/user-attachments/assets/35da4936-72a5-4086-86ad-5d5850a58acb)
    - [x] [ShowBrokenReferencesDialogView](https://github.com/user-attachments/assets/30b522ac-de42-409a-9cd2-8e3651a584b8)
  - [x] [FolderPathInputDialogView](https://github.com/user-attachments/assets/37f7b51f-8021-415f-981c-5ba2017b0c1b)
  - [x] [InputDialogView](https://github.com/user-attachments/assets/ce342187-dd69-4a28-ae2b-fce5f7117b4a)
  - [x] `InstallerWizardView`
    - **removed** as I could not find any usage
  - [x] [NewFileView](https://github.com/user-attachments/assets/e83ca0af-5236-410d-b694-b8eda47b929b)
  - [x] [ProjectSettingsDialog](https://github.com/user-attachments/assets/35ec78b7-f297-4a7a-923f-1e28d8dc6dfa)
  - [x] [ProjectWizardDialog](https://github.com/user-attachments/assets/a771e941-5c60-4468-ba94-83e0e4f3a9a7)
  - [x] [ScriptManagerView](https://github.com/user-attachments/assets/d8d19474-2a85-4af5-acbb-acd484d3bb40)
    - added icons in buttons `Add` and `Update Scripts`.
  - [x] [SoundModdingView](https://github.com/user-attachments/assets/a0724be3-fbee-4232-87c8-744e2e4bcf4e)
    - **removed** GridSplitter elements, useless imo
    - fitted event properties
  - [x] [TypeSelectorDialog](https://github.com/user-attachments/assets/b37560f7-e18d-4484-ae54-0bce02e30989)
    - renamed button `OK` to `Create`, afaik it is more appropriate
- [x] Documents
  - [x] `CodeEditorView`
    - **removed** view, no usage found
    - **removed** `MyEditorCollection.cs`, no usage found
  - [x] [RDTDataView](https://github.com/user-attachments/assets/ae708469-9ae5-445d-8aa4-5c6e230cc4cb)
    - **removed** content of `footer`
    - moved RedType text in `header`
    - moved Load References button in `header`
    - aligned all elements using a grid in `header`
  - [x] `RDTGraphView`
    - run XAML Styler
    - is only `GraphEditorView` relevant regarding `ContextMenu`?
  - [x] `RDTGraphView2`
    - run XAML Styler
  - [x] [RDTInkAtlasView](https://github.com/user-attachments/assets/ed0c8958-9c80-4936-bca6-b32dd5487d75)
    - **removed** HandyControl styles
    - added icons in ContextMenu
  - [x] [RDTLayeredTextureView](https://github.com/user-attachments/assets/ff95b993-b210-4bbb-bec7-a1d8f854e25c)
  - [x] [RDTMeshView](https://github.com/user-attachments/assets/61768d72-7193-42d3-b2fb-33aeef1dba59)
    - added icons
    - improved layout and alignment
    - changed to yellow color for experimental buttons, show experimental in tooltip
    - **disabled** CTRL style on Material button, needs to be fixed in its own PR
  - [x] [RDTTextureView](https://github.com/user-attachments/assets/4e55752a-b16a-4226-8840-065dad176314)
    - added icons in ContextMenu
  - [x] ~~`RDTTextView`~~
    - **removed** no usage found, text files are handled by the OS in `AppViewModel`
  - [x] [RDTWidgetView](https://github.com/user-attachments/assets/76d00f0e-0d04-46c7-9396-da666ddcff5a)
    - added some icons
    - renamed "Export inkWidget as XML" to "Export as XML"
    - improved alignment
  - [x] [RedDocumentView](https://github.com/user-attachments/assets/646eb147-4b85-4a76-870e-39e4726db3eb)
    - changed path to be relative to project, instead of absolute path.
  - [x] [RedDocumentViewMenuBar](https://github.com/user-attachments/assets/2b50f602-30d9-459b-96bd-ec5bdee1f513)
    - added some icons
    - aligned all menu items
    - fixed integration of search bar
    - refactored styles
  - [x] ~~`ScriptDocumentView`~~
    - **removed** in #1995 
  - [x] [WScriptDocumentView](https://github.com/user-attachments/assets/437bbcea-2ceb-4003-bf95-e90d0d549992)
    - added icons
- [x] GraphEditor
  - [x] [GraphEditorView](https://github.com/user-attachments/assets/adbaf9ab-22bc-4c3e-bad7-7294f9a473e6)
    - run XAML Styler
    - added icons in `ContextMenu`
- [x] Importers
  - [x] [ImportView](https://github.com/user-attachments/assets/ebbd5ed6-f362-40b4-b7d2-0ad875caf6e8)
    - **removed** redundant separators
- [x] Exporters
  - [x] [ExportView](https://github.com/user-attachments/assets/d2d580f0-bac2-45cb-a199-3f65fa4b1a42)
    - **removed** redundant separator
- [x] Others
  - [x] `FileIconView`
  - [x] `ImageCanvas`
  - [x] `LoadingTextControl`
  - [x] `PolygonWaveFormControl`
  - [x] `PolylineWaveFormControl`
  - [x] `SpectrumAnalyser`
- [x] Templates
  - [x] `BitfieldTemplateView`
  - [x] [CurveEditorWindow](https://github.com/user-attachments/assets/74866414-7ab4-4cb6-a2b0-5d93ce3e931b)
      - refactored using WizardControl and WKit style (like in Dialogs > Windows)
      - moved min/max ranges in rows
      - moved cursor position in top-right corner of canvas
      - changed formats with always 2 decimals (should use current locale)
      - fixed selection of a point (color feedback)
      - changed colors to use WolvenKit resources
      - removed redundant labels (top / right), let me know
      - getting ready for #1957 
  - [x] [CustomCollectionEditorView](https://github.com/user-attachments/assets/fed3b308-fdcb-4d4e-9c15-bafa125d14c1)
  - [x] [EnumTemplateView](https://github.com/user-attachments/assets/ee006044-171c-4e96-8af5-0af54b7930c2)
  - [x] `HandleTemplateView`
    - **removed**, no usage found afaik
  - [x] [PathEditorView](https://github.com/user-attachments/assets/30e140e4-f49d-4609-a809-e836efcfd1ef)
    - changed style of button
  - [x] `RedBaseTypeEditor`
    - **removed**, no usage found
  - [x] [RedBoolEditor](https://github.com/user-attachments/assets/a1bd67ae-5c98-4608-aed8-fa3edcb15aab)
  - [x] [RedChunkMaskEditor](https://github.com/user-attachments/assets/636925f8-715b-4f4e-a69b-185188635672)
  - [x] [RedCNameEditor](https://github.com/user-attachments/assets/f3214f0c-0df2-48da-86b6-41511e1875fc)
  - [x] `RedCollectionEditor`
    - **removed**, no usage found including child dependency and ViewModel
  - [x] `RedColorEditor`
  - [x] `RedCurveEditor`
  - [x] [RedCurvePointEditor](https://github.com/user-attachments/assets/2bd9c0e1-2266-4cb4-b74c-f5146c39f82d)
    - changed formatting of X values for alignment (reduce from 9 to 6 decimals)
    - aligned X values to the right
  - [x] `RedFixedPointEditor`
  - [x] `RedFloatEditor`
  - [x] `RedIntegerEditor`
  - [x] [RedLocalizationStringEditor](https://github.com/user-attachments/assets/9681c43f-475e-4f18-84e3-4343fdef7998)
  - [x] `RedNodeRefEditor`
  - [x] [RedQuaternionEditor](https://github.com/user-attachments/assets/af298d4d-fbed-4da7-bd87-2d9dffbc9f12)
  - [x] [RedRefEditor](https://github.com/user-attachments/assets/71761652-7190-45eb-8dc6-112e17fc6ad9)
  - [x] `RedStringEditor`
  - [x] `RedTweakEditor`
  - [x] [RedTypeView](https://github.com/user-attachments/assets/94570452-7f24-48e6-bd3a-aa07a2436e90)
  - [x] `RedUlongEditor`
  - [x] [RedVector2Editor](https://github.com/user-attachments/assets/8bcc61b0-5fe9-4c88-a689-c05f0229b398)
  - [x] [RedVector3Editor](https://github.com/user-attachments/assets/47a9f640-9c77-495b-b0d4-8add42844a7c)
  - [x] [RedVector4Editor](https://github.com/user-attachments/assets/67eb993c-3959-4a5a-88d7-c0d141092e62)
  - [x] `RedVectorColorEditor`
  - [x] [RedWorldPositionEditor](https://github.com/user-attachments/assets/af298d4d-fbed-4da7-bd87-2d9dffbc9f12)
  - [x] [TrimmingTextBox](https://github.com/user-attachments/assets/4b5ac405-d186-4385-95e5-0637315dd512)

**Additional notes:**
Closes #604

- HandyControl could be removed later and replaced with a custom template.
- [x] Use XAML Styler extension by all devs.
- [x] Configure XAML Styler rules, if possible, with the following style:
```xaml
<!-- Inline property when only 1 is defined -->
<TextBlock x:Name="MyText" />

<!-- Always flatten properties otherwise -->
<TextBlock
    x:Name="MyText"
    FontSize="12">
</TextBlock>

<!--
   List style/appearance properties first
   Followed by data/event/command properties last
-->
<Button
    Margin="4"
    Foreground="Green"
    FontSize="14"
    Click="Button_OnClick">
</Button>
```

**Screenshot links:**
Screen resolution: 1080p
Scale UI: 150%

**Reviews:**
From @seberoth 
- [ ] change + scale checkmarks in [MenuBarView](https://github.com/user-attachments/assets/6127a7da-fd03-48c3-ba7a-a43bf6d53481).
- [x] scale tab header's height and icons [DockingAdapter](https://github.com/user-attachments/assets/9ee096e0-d432-4410-bdbf-13a8cc9c391c)
- [x] downscale icons/buttons in both [RibbonView + ProjectExplorer](https://github.com/user-attachments/assets/378c7844-9759-49d0-98a6-fbdff0f09adb) and in [Log wscript shortcut](https://github.com/user-attachments/assets/db3bc97d-c3ad-4a9a-a2db-2e917820828c).
  - [RibbonView](https://github.com/user-attachments/assets/ad26caf0-5510-45ed-81cc-99675bfa2634)
  - [ProjectExplorer](https://github.com/user-attachments/assets/dbf1e0c5-66b4-421f-9f35-46db7864aea6)
  - [LogView](https://github.com/user-attachments/assets/497a3c9a-5825-4cea-b22a-8acecab5de63) at 150%
- [x] scale [Scriptable Menus](https://github.com/user-attachments/assets/33ff6d22-8032-4b46-a847-2f9f2c137fbc).
  - no screenshot
- [x] bad UI when loading [TweakDB Browser](https://github.com/user-attachments/assets/f5845533-208f-491f-9201-cd3e7b24e841).
  - [TweakDB Browser](https://github.com/user-attachments/assets/c4948ada-fad0-4859-ab55-187929689e9b)
- [ ] implement restart after changing Scale UI option, see if it fixes this issue:
> Changing scaling somehow (partly) resets my project layout.
First time it got reset to default, now the disabled windows (lockey/tweakdb browser, properties) keep reappearing.

### CODE REVIEW

**Comment by poirierlouis** [comment]
In `ModsView`, is it ok if I move buttons next to the header `Mod Manager` (like in Settings)?
I'm thinking about moving/reshaping `Refresh`, `Deploy` and `Launch game`.
And also put `Open Mods Folder` next to the checkbox.

image

**Comment by manavortex** [comment]
Hey there, 

great work so far! A few things I noticed: 

image
CR2W editor is a little too squished together now

by contrast, the context menu looks insanely roomy: 
image

**Comment by poirierlouis** [comment]
I did not implemented the scale feature based on user's screen resolution at startup. I think it might be better at first, even in nightly to keep things at 100% for now. Can be implemented in another PR later.
Also, changing scale from Settings should force restart of WKit.

I did not write any instructions for now regarding XAML Styler. I'll write something in CONTRIBUTING.
But basically, I added a `XamlStyler.vssettings` file in `WolvenKit/`. After installing XAML Styler, you should only need to import this file using VS settings importer. Don't know yet about how it behaves in Rider though.

**Comment by seberoth** [comment]
1. Still have the issue that my layout got reset after changing the Scale while the porject is open.
2. Some fonts are only scaled after a restart
  a. See image
  b. Code Editor isn't scaled at all, which is fine I think. We could add a seperate zoom for that later.

grafik

**Comment by poirierlouis** [comment]
> 1. Still have the issue that my layout got reset after changing the Scale while the porject is open.
> 
>     2. Some fonts are only scaled after a restart
>        a. See image
>        b. Code Editor isn't scaled at all, which is fine I think. We could add a seperate zoom for that later.
> 
> 
> grafik

1. Will be fixed by forced restart, I tried before I couldn't force these font resizes due to Syncfusion.
2. Code Editor? You mean about WScript documents?

**Comment by poirierlouis** [comment]
1. So, I fixed it after looking back at it. All yellow parts of your screenshot should scale now without a restart required.
2. WScript document editor was supposed to scale the font size, but there was a typo in resource, now it is fixed.

**Review by manavortex — APPROVED** [review]
LGTM. Exciting!!

**Pull request merged**
