### PR TITLE
New default layout suggestion

### PR DESCRIPTION
**Pull request by manavortex**
# New default layout suggestion

Asset browser is now pinned by default
Import and export tool are visible by default

What do y'all think?

image

### CODE REVIEW

**Comment by seberoth** [comment]
Not sure if we should assume 2560x1440 as default resolution.
I think, many users still have FullHD (like me) and then the actual file area is rather small.
grafik

**Comment by manavortex** [comment]
It could probably benefit from some re-scaling for smaller displays, yeah.

**Comment by effs** [comment]
AB benefits more from height than width, Editor from both. And since you're less likely to use Export and Import at the same time, they can be tabbed to save space. So I'd still put AB in a column on the right stacked with either E/I or Preview below. Gives a bit more flexibility on width.

**Comment by manavortex** [comment]
Most hardcore users whose layouts I've seen use Import/Export simultaneously, and I don't think we benefit much from height because you'd probably use the filter by <15 items anyway, wouldn't you? 

Open to suggestions though, push one?

**Comment by effs** [comment]
But default is not for hardcore users or those who know how to search ultra-efficiently, default is for My First Mod :)

**Comment by manavortex** [comment]
Fair point :)

**Review by rfuzzo — APPROVED** [review]
why not

**Pull request merged**
