### PR TITLE
⚙️ Settings Migration Refactor for V3 Plus Experimental Setting

### PR DESCRIPTION
**Pull request by effs**
Made the migration logic a bit more uniform.

The experimental setting isn't used yet, need to thread it through.

Related to #1197

### CODE REVIEW

**Comment by seberoth** [comment]
Why bump to v3 if you just add an option?
Just add it to the Dto and set the default value to true.
Also cuurently it is only set to true on migration and not for new users

**Review by rfuzzo — APPROVED** [review]
Thanks, we also have appsettings.json for feature flags btw

**Review by rfuzzo — CHANGES_REQUESTED** [review]
changing to request changes to address Seb's points. I like the more general version migration though. 
but: 
1. Add true to the default value
2. Don't bump the version

**Comment by effs** [comment]
> Thanks, we also have appsettings.json for feature flags btw

Oh, I had missed that, thanks! This was meant more for user-togglable features. Alternative in this case might be to persist the MeshArgs selection instead, but that'll still reset between restarts…

**Comment by effs** [comment]
Can live without this

**Pull request closed without merging**
