### PR TITLE
Refactoring/archive manager replace with original

### PR DESCRIPTION
**Pull request by manavortex**
# Project browser: "Replace with original" 

Can now take a search scope as parameter (will default to currently-active scope). Context menu entry will search game and mods, but consider game first.

### CODE REVIEW

**Comment by seberoth** [comment]
If you want to refactor game file loading, maybe you should work together with rfuzzo on #1616 
Also don't quite understand why you added an new constructor to `WolvenKitException` and marked it obsolete directly.

**Comment by manavortex** [comment]
> Also don't quite understand why you added an new constructor to `WolvenKitException` and marked it obsolete directly.

Autocomplete/doc reasons. Expectation is that I do new Exception(string message) - I get better feedback from the UI this way

**Comment by seberoth** [comment]
But you won't get any feedback for `throw new Exception(string message)`. Then you would need to mark `Exception` as obsolete, not `WolvenKitException`.

**Comment by manavortex** [comment]
Right, but that case will also not trigger your LogWrapper, so I consider that a win :D

**Comment by seberoth** [comment]
Tbh, I consider this as a lose. Now it allows negative error codes but they all get ignored/filtered out later.

**Comment by manavortex** [comment]
Sure, then let's nuke it :)

**Comment by manavortex** [comment]
Nuked it. Not sure about collaborating with Fuzzo, since my changes (hopefully) touch a whole different part of the file loading..ß

**Review by rfuzzo — APPROVED** [review]
👍

**Pull request merged**
