### PR TITLE
Settings: exclude archives from scan

### PR DESCRIPTION
**Pull request by manavortex**
# Settings: exclude archives from scan

### CODE REVIEW

**Comment by DefectiveSoftworks** [comment]
@manavortex Hello good morning choomba! Any idea why 'basegame_AMM_Props' cannot be opened? Is it too big or is it encrypted? If it's encrypted, are there any further details on how to encrypt mod archives? Many and most thanks!

**Comment by manavortex** [comment]
@DefectiveSoftworks: It's outdated and Wolvenkit doesn't know how to read the files anymore. Might even have been packed with an ancient CLI. It's nothing on purpose.

**Comment by DefectiveSoftworks** [comment]
> @DefectiveSoftworks: It's outdated and Wolvenkit doesn't know how to read the files anymore. Might even have been packed with an ancient CLI. It's nothing on purpose.

@manavortex Thanks for the quick response!

Sweeeeet Christmas! I would never have guessed that... I been scratching my head raw about it for a week straight now hahah!

* Initially I thought 'basegame_AMM_Props' was corrupted. So, I deleted the archive and updated the AMM LUA code to make it optional. I saw most of AMM functionality worked without it except a few odds and ends, poses, and animations. I came to understand that the game was somehow reading the archive.

* I checked the modding wikis for details on archive encryption and couldn't find anything.

* I got to the point where I decided to dig through the source of Wolvenkit to attempt to further understand. That's when I came across: [AssetBrowserViewModel.cs#L1134](https://github.com/WolvenKit/WolvenKit/blob/831bd73f5ee80030786c024fda5505adfec0ef85/WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs#L1134) while debugging. I didn't put that Setting and I removed it only to discover I was got similar issues in Wolvenkit and cp77tools about bin files.

Wolvenkit .bin file errors in Asset Browser

Investigating the version history led me to these commits and this pull request. I have a much clearer understanding now that it isn't any encryption by the mod author. Do you think I could use an older version of Wolvenkit or cp77tools to read the files?

Sorry for giving you the entire breakdown of what I've done to get this far I just wanted to explain the steps I took. I'm attempting to understand how Workspot Poses and Animation Entity files are created *(e.g. base\amm_workspots\entity\workspot_anim.ent, base\eap_64189045\controller\entity_01.ent, etc)*.

SELECT DISTINCT a.anim_ent FROM `workspots` a;

Wolv's Easy AMM Poses Tool doesn't appear like it is open source anymore. The repository responds with a 404 page here on Github.

Many and most thanks for everything!

**Comment by manavortex** [comment]
I've talked to the mod author about it, and he's exactly as fucked as everyone else. If that archive ever breaks, AMM is in for a world of pain lol

**Comment by DefectiveSoftworks** [comment]
> I've talked to the mod author about it, and he's exactly as fucked as everyone else. If that archive ever breaks, AMM is in for a world of pain lol

Oof, ouch! I can imagine the pain spread far and wide hahah! AMM remains one of the most popular mods in the Cyberpunk 2077 modding scene. If this archive goes bork bork, whelp everyone who _depends_ on AMM is going to feel it like a subtle kick in the nads.

**Comment by DefectiveSoftworks** [comment]
Very true indeed. Chaos serves as a great motivator hahah! Yeah, going through each and every older version, installing the correct .NET SDK dependency, attempting to figure out which one can read the files seems really troublesome and nightmare inducing hahah.

**Comment by Simarilius-uk** [comment]
couldnt you look at the upload date, find the wkit release that was current then and extract to raw with that?

**Comment by DefectiveSoftworks** [comment]
> couldnt you look at the upload date, find the wkit release that was current then and extract to raw with that?

Good idea @Simarilius-uk! Looks like the older versions of AMM are listed and available for download. I'll try that to see if I'm able to get what I need. Many and most thanks!

**Comment by manavortex** [comment]
Pretty sure you just need a _WolvenKit_ version from around that time ;)

If you manage to re-pack the archive with a recent version, or extract the files, do let me know. I'm sure Max would be relieved!

**Pull request merged**
