### PR TITLE
feature/searchbar for CR2W editor

### PR DESCRIPTION
**Pull request by manavortex**
# Initial implementation of CR2W editor search bar 

image
image

### CODE REVIEW

**Comment by poirierlouis** [comment]
Could you reuse XAML from search bar present in AssetBrowser and ProjectExplorer to have the same UI?

**Comment by manavortex** [comment]
Could probably steal the styles, yeah. Maybe you'd like to define a neat input box style that we can all inherit from somewhere? :D

**Comment by poirierlouis** [comment]
I can't take a look right now but I think there is already one used in the views I mentioned. It also supports the erase button/icon iirc.

**Comment by rfuzzo** [comment]
image
One thing I noticed: the search bar clips with the tab bar a bit

**Comment by rfuzzo** [comment]
request: it should search case-insensitively (right now it is case-sensitive)

**Comment by rfuzzo** [comment]
Requests:
- [ ] it should search case-insensitively (right now it is case-sensitive)
- [ ] and (maybe for a future feature): option to search for variable names (right now it searches for values only as far as I can see)

and great work! 👍 this is amazing

**Comment by manavortex** [comment]
> Requests:
> 
>     * [ x]  it should search case-insensitively (right now it is case-sensitive)
`StringComparison.OrdinalIgnoreCase` exists! Who'd have thought :))

>     * [ ]  and (maybe for a future feature): option to search for variable names (right now it searches for values only as far as I can see)
Yes, it's value only (and it's not 100% reliably because it only searches through `Description`, `Value`, and whatever StringHelper.ToString spits out). 
I would love to give the RTTI-types a proper ToString implementation, but I have no idea how to achieve that. I keep forgetting which of these files are generated and which aren't :D 

> and great work! 👍 this is amazing
Thank you! I've wanted this forever and ever and ever

**Pull request merged**
