### PR TITLE
Update RTTI types for 1.30

### PR DESCRIPTION
**Pull request by WopsS**
Updated the RTTI types to 1.30.

One warning I saw was this:

```
 'animAnimNode_StateMachine.DebugName' hides inherited member 'animAnimNode_Base.DebugName'.
```

Not sure if that's good or not, @rfuzzo should check it.

### CODE REVIEW

**Review by rfuzzo — APPROVED** [review]

**Comment by rfuzzo** [comment]
> One warning I saw was this:
> 
> ```
>  'animAnimNode_StateMachine.DebugName' hides inherited member 'animAnimNode_Base.DebugName'.
> ```
> 
> Not sure if that's good or not, @rfuzzo should check it.

Yeah I know about these, the unit tests will tell.

**Comment by rfuzzo** [comment]
@WopsS I updated the assemblyversion and added the game version as InformationalVersion. Does that look good to you?

**Comment by WopsS** [comment]
> 
> 
> @WopsS I updated the assemblyversion and added the game version as InformationalVersion. Does that look good to you?

Yes, seems good. You could use semver `1.3.0` if that would be more simple, they use that too internally.

**Comment by rfuzzo** [comment]
> 
> 
> > @WopsS I updated the assemblyversion and added the game version as InformationalVersion. Does that look good to you?
> 
> Yes, seems good. You could use semver `1.3.0` if that would be more simple, they use that too internally.

great. good idea

**Pull request merged**
