### PR TITLE
fix: Don't analyze archives when loading via cli

### PR DESCRIPTION
**Pull request by seberoth**
fix: Don't analyze archives when loading via cli

### CODE REVIEW

**Comment by poirierlouis** [comment]
LGTM.

**Comment by poirierlouis** [comment]
I wonder, as I'm not use to cli, no subsequent tasks/features requires archive files to be analyzed?

**Comment by seberoth** [comment]
> I figure Tasks are only related/used with CLI?

Yeah. Could also expose that flag, but would do that as a new feature (to allow it for mod archives for example).
But for now just disabling it. Should be the default bahviour anyway

**Comment by poirierlouis** [comment]
Alright thanks for the clarification. Yes make sense to add such feature in another PR.

**Pull request merged**
